name: Accept GH Invitations Action

on:
  workflow_dispatch
  # You can add a schedule here

jobs:
  Execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # No dependencies needed yet
    - name: Run Script
      run: node app.js --token ${{ secrets.INVITE_ACCESS_TOKEN }}
